### PR TITLE
Added JUnit parser

### PR DESCRIPTION
**Pull request by chemfy**

### CODE REVIEW

**Comment by tomasbjerre** [comment]
I'm not sure about this. Is JUnit really static code analysis?

What is the use case? Are there not other tools supporting same use case?

**Comment by chemfy** [comment]
Hello. No, JUnit is not static analysis. 
I started using the top level jenkins plugin to get build results to get posted on pull requests. I was surprised that the plugin didn't support posting test results. I considered my options for getting this support and thought the easiest would be to get it added here.

I see the use case as the same as for the static analysis. To make sure the pull request creator notices those. I haven't found any other tool for this. Every other tool requires the user to goto Jenkins to see what is wrong.

I don't see why this should only be about static analysis, but vision/usage of it may not be the same as yours.

**Comment by tomasbjerre** [comment]
"...requires the user to goto Jenkins to see what is wrong" that is a good point!

And you are aware that only changed files will currently be commented? So the failed test case has to have been touched.

Or this also requires https://github.com/tomasbjerre/violation-comments-lib to be further developed to support some option like `commentWithEveryViolation` that would not only comment changed files, but comment with every violation.

**Comment by chemfy** [comment]
I'm currently using the publisher to bitbucket with "commentOnlyChangedContent: false". Which I think would ensure that all failures would be commented. 
But no, I did not consider that. Should it be some type of ability to have, parser specific custom settings that the use could configure?

**Comment by tomasbjerre** [comment]
I don't think it has to be parser specific. It can be on same level as `commentOnlyChangedContent`. Assuming most users are using pipelines, they can just use the plugin twice if they want different configs for different parsers.

Regarding the behavior of `commentOnlyChangedContent`. It changes if **all violations** found on a changed file should be commented or only the violations found in the **changed content of the file**.

**Comment by tomasbjerre** [comment]
Actually, perhaps `commentOnlyChangedFiles` is a better name than `commentWithEveryViolation` to use in `violation-comments-lib`. And have it `true` by default.

So in this case it would be set to `false` and have every violation commented.

**Comment by chemfy** [comment]
Oh ok, I misunderstood how commentOnlyChangedContent worked, but now I know.

I can look at adding that to violation-comments-lib over the weekend.

**Comment by tomasbjerre** [comment]
Sounds good.

The method `void createCommentWithAllSingleFileComments(String string);` here:
https://github.com/tomasbjerre/violation-comments-lib/blob/master/src/main/java/se/bjurr/violations/comments/lib/CommentsProvider.java

Can probably be renamed to `void createPullRequestComment(String string);`.

As that is what it does, it creates a comment on the PR, not on a file. And then use that method for the commenting.

Also, try not to refactor the API (even if it is far from perfect) as that will result in a lot of docs to be updated and most likely future support issues. This should be possible to implement and still being totally backwards compatible.

**Comment by tomasbjerre** [comment]
Released in 1.94

**Pull request merged**
