### PR TITLE
Fix regex to allow for installation of MsBuild in Program Files (x86)

### PR DESCRIPTION
**Pull request by arontsang**
fixes https://github.com/tomasbjerre/violations-lib/issues/182

### CODE REVIEW

**Comment by arontsang** [comment]
@tomasbjerre Hi Tomas, I can't seem to get this PR to build correctly. Seems to be some kind of code formatting rule that prevents me from building.

Not sure what the rule is, can you please take a look?

**Comment by tomasbjerre** [comment]
> @tomasbjerre Hi Tomas, I can't seem to get this PR to build correctly. Seems to be some kind of code formatting rule that prevents me from building.
> 
> Not sure what the rule is, can you please take a look?

The code will be formatted when you do `./gradlew googleJavaFormat`

Unless you are using Java 17: https://github.com/tomasbjerre/gradle-scripts/blob/master/src/main/resources/main.gradle#L132

**Comment by arontsang** [comment]
> > @tomasbjerre Hi Tomas, I can't seem to get this PR to build correctly. Seems to be some kind of code formatting rule that prevents me from building.
> > Not sure what the rule is, can you please take a look?
> 
> The code will be formatted when you do `./gradlew googleJavaFormat`
> 
> Unless you are using Java 17: https://github.com/tomasbjerre/gradle-scripts/blob/master/src/main/resources/main.gradle#L132

Sigh...silly me, using the LTS Java. I probably should have Java 8 like everyone else...

**Comment by arontsang** [comment]
@tomasbjerre Thank you for your help. Built successfully now.

**Comment by tomasbjerre** [comment]
> > > @tomasbjerre Hi Tomas, I can't seem to get this PR to build correctly. Seems to be some kind of code formatting rule that prevents me from building.
> > > Not sure what the rule is, can you please take a look?
> > 
> > 
> > The code will be formatted when you do `./gradlew googleJavaFormat`
> > Unless you are using Java 17: https://github.com/tomasbjerre/gradle-scripts/blob/master/src/main/resources/main.gradle#L132
> 
> Sigh...silly me, using the LTS Java. I probably should have Java 8 like everyone else...

There is a newer version of the Google Java Format plugin that runs on 17, but it will not run on 8. So if upgrading build script to that I can no longer verify builds with 8.... it is not perfect :)

**Comment by tomasbjerre** [comment]
Can you supply a log that is currently not possible to parse:
https://github.com/tomasbjerre/violations-lib/tree/master/src/test/resources/msbuildlog

And add test case here:
https://github.com/tomasbjerre/violations-lib/blob/master/src/test/java/se/bjurr/violations/lib/MSBuildLogTest.java

The test case that is currently implemented seems to have `MSBuild` in `C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild` so I am not exactly sure what this fixes.

**Comment by arontsang** [comment]
@tomasbjerre The new SDK style projects have a lot more warnings.

I've added a unit test to test for incompatible nuget dependencies and incompatible 'in solution' dependencies.

**Comment by tomasbjerre** [comment]
Thanks, releasing this now.

**Comment by arontsang** [comment]
@tomasbjerre Thank you very much. Very fast response.

I would also appreciate it if you bump the Jenkins plug in as well.

**Pull request merged**
